#!/bin/sh
#
#  Inspired by nbdswapd from the ltsp-server package.

## swap file and size (in MB):
SWAP=$(mktemp)
SIZE="64"

## create swap file:
dd if=/dev/zero of=$SWAP bs=1024k count=0 seek=$SIZE 2> /dev/null

## start nbd-server:
nbd-server 0 $SWAP -C /dev/null > /dev/null 2>&1

## remove swap file:
rm -f $SWAP
