#!/bin/bash
#
#  Compare with the corresponding FAIBASE script.
#

set -e

fcopy -v /etc/hosts

## fetch template and fill in nameserver's IP address:
fcopy -v /etc/resolv.conf
IP=`host ns | tail -n 1 | awk '{print $NF}'`
sed -i "s/NAMESERVER/$IP/" $target/etc/resolv.conf

## timezone
echo $TIMEZONE > $target/etc/timezone
cp -f /usr/share/zoneinfo/${TIMEZONE} $target/etc/localtime

# create keyboard layout table
$ROOTCMD bash -c "echo 'console-data console-data/keymap/full select $KEYMAP' | debconf-set-selections"
$ROOTCMD install-keymap $KEYMAP || true
