#! /bin/bash

# assign classes hosts

# Most of the classes in $MAINSERVER_* should be self-contained and not
# specific to a given setup.  Use the SERVER_* or CLIENT_* class for
# all setup-specific details.

##
##   Setup A
##   =======
##
##   Mainserver variants (cf. wiki documentation):
##
##     INT_GATEWAY | EXT_GATEWAY  -->  internal/external gateway
##
##     *LVM6_A | *LVM7_A DISKLESS_SERVER  -->  diskless client server
##
##     LVM*_A | RAIDLVM*_A  -->  RAID1 (mirroring)
##

MAINSERVER_A="LVM6_A LOG_SERVER PROXY NTP_SERVER DNS_SERVER NFS_SERVER \
LDAP_CLIENT LDAP_SERVER KERBEROS_CLIENT KERBEROS_KDC KDC_LDAP SERVER_A INT_GATEWAY"

WORKSTATION_A="LVM5_A LOG_CLIENT LDAP_CLIENT NFS_CLIENT KERBEROS_CLIENT CLIENT_A"


## Setup B, not yet implemented:
MAINSERVER_B="NTP_SERVER DNS_SERVER LDAP_SERVER KERBEROS_KDC SETUP_B"



# Use a list of classes for your machine:
case $HOSTNAME in
    faiserver)
	echo "FAIBASE DEMO FAISERVER" ;;
    demohost)
	echo "FAIBASE DHCPC DEMO" ;;
    gnomehost)
	echo "FAIBASE DHCPC DEMO XORG GNOME";;
    atom*)
	echo "FAIBASE DHCPC DEMO" ;;
    bear)
	echo "FAIBASE DHCPC LVM_XEN_SERVER XEN" ;;
    puma)
	echo "FAIBASE DHCPC RAID_XEN_VIRTUAL" ;;
    mainserver)
	echo "FAIBASE FAISERVER $MAINSERVER_A" ;;
    workstation*)
	## You might want to add some localization class like:
	# echo "FAIBASE DHCPC $WORKSTATION_A XORG DESKTOP GERMAN" ;;
	echo "FAIBASE DHCPC $WORKSTATION_A XORG DESKTOP" ;;
    diskless)
        echo "$WORKSTATION_A XORG DISKLESS_CLIENT"
        ## skip GRUB_PC below:
        exit 0 ;;
    *)
	echo "FAIBASE DHCPC" ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB_PC

exit 0
