#!/bin/bash

set -e

ainsl $target/etc/exports "/srv/fai/nfsroot  ${FAINETMASK}(async,ro,no_subtree_check,no_root_squash)"
ainsl $target/etc/exports "/srv/fai/config   ${FAINETMASK}(async,ro,no_subtree_check,no_root_squash)"
